export type Workspace = { id: string; name: string; path: string; createdAt: number; lastOpenedAt: number }
export type FileNode = { id: string; name: string; path: string; relativePath: string; kind: 'file' | 'folder'; children?: FileNode[] }
export type NoteMeta = { path: string; title: string; summary?: string; tags: string[]; wordCount: number; updatedAt: number }
export type EditorMode = 'write' | 'preview' | 'split'
export type ThemeId = 'obsidian' | 'paper' | 'midnight' | 'solar' | 'forest'
export type AiPreset = { id: string; label: string; prompt: string; scope: 'selection' | 'document' | 'paragraph' }
export type PluginPermission = 'filesystem' | 'ai' | 'markdown' | 'ui' | 'metadata' | 'commands'
export type PluginManifest = { id: string; name: string; version: string; description: string; author?: string; main?: string; permissions: PluginPermission[]; contributes?: { commands?: PluginCommandContribution[]; markdownIt?: string[]; themes?: ThemeContribution[]; aiPresets?: AiPreset[]; panels?: PluginPanelContribution[] } }
export type PluginCommandContribution = { id: string; title: string; category?: string; when?: string }
export type PluginPanelContribution = { id: string; title: string; location: 'left' | 'right' | 'bottom' }
export type ThemeContribution = { id: string; label: string; cssFile?: string }
export type PluginRecord = PluginManifest & { enabled: boolean; installedPath?: string; builtin?: boolean }
export type AppSettings = { theme: ThemeId; editorMode: EditorMode; syncScroll: boolean; splitRatio: number; fontFamily: 'sans' | 'serif' | 'mono'; aiProvider: 'offline' | 'openai-compatible' | 'custom-plugin'; aiEndpoint?: string; aiModel?: string }
export type SearchResult = { path: string; title: string; excerpt: string; score: number }
export type CreateEntryInput = { workspaceId: string; parentPath: string; name: string; kind: 'file' | 'folder' }
export type RenameEntryInput = { workspaceId: string; path: string; nextName: string }
export type DeleteEntryInput = { workspaceId: string; path: string }
export type SaveFileInput = { workspaceId: string; path: string; content: string }
export type AiActionInput = { presetId?: string; prompt?: string; text: string; document?: string; path?: string }
export type AiActionOutput = { text: string; tags?: string[]; summary?: string }
